language: minimal
os: linux
dist: manjaro
services:
  - docker
jobs:
  include:
    - if: branch = master
      stage: conan_deploy
      script:
        - sudo apt-get install -y python3 python3-pip python3-setuptools
        - pip3 install wheel
        - pip3 install conan
        - cmake --version
        - make conan_remote
        - make conan_create
        - VERSION=0.0.1 make conan_upload
notifications:
  email: false
branches:
  except:
  - legacy
  # safelist
  only:
  - master
  - /experimental(-.*)?/
  - stable
