language: minimal
os: linux
dist: xenial
services:
  - docker
jobs:
  include:
    - if: branch = master
      stage: conan_deploy
      script:
        - sudo apt-get install -y python3 python3-pip python3-setuptools
        - mkdir ~/temp && cd ~/temp
        - wget https://cmake.org/files/v3.19/cmake-3.19.1.tar.gz
        - tar -xzvf cmake-3.19.1.tar.gz
        - cd cmake-3.19.1/
        - ./bootstrap
        - make
        - sudo make install
        - cd ../..
        - pip3 install wheel
        - pip3 install conan
        - ls
        - make conan_remote
        - make conan_create
        - VERSION=0.0.1 make conan_upload
notifications:
  email: false
branches:
  except:
  - legacy
  # safelist
  only:
  - master
  - /experimental(-.*)?/
  - stable
