language: minimal
os: linux
dist: xenial
services:
  - docker
jobs:
  include:
    - if: branch = master
      stage: conan_deploy
      script:
        - docker build -t $DOCKER_USERNAME/cppkg-cmake:travis-${TRAVIS_COMMIT} -f Dockerfile.conan .
        - docker run -e CONAN_USR=${CONAN_USR} -e CONAN_PWD=${CONAN_PWD} --rm $DOCKER_USERNAME/cppkg-cmake:travis-${TRAVIS_COMMIT}
notifications:
  email: false
branches:
  except:
  - legacy
  # safelist
  only:
  - master
  - /experimental(-.*)?/
  - stable
