FROM mkaichen/bionic_conan_cmake:latest

ENV APP_DIR /usr/src/cppkg

# working directory
RUN mkdir -p $APP_DIR
WORKDIR $APP_DIR
COPY . $APP_DIR

RUN make conan_remote

ENTRYPOINT [ "VERSION=0.0.1", "make", "conan_create_n_upload" ]
